# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: VulnerableWebApp
    type: github
    endpoint: metalstormbass
    name: metalstormbass/VulnerableWebApp

stages:
  - stage: Security_Test_Terraform_IAC
    jobs:
    
    - job: Terraform_Security_Scan  
      steps:
        - checkout: VulnerableWebApp
        - checkout: self
        - bash: |
              ls
              chmod +x ./shiftleft
              ./shiftleft iac-assessment -r 201981 --path ./
              ./shiftleft sourceguard -s VulnerableWebApp/
          env:
           CHKP_CLOUDGUARD_ID: $(CHKP_CLOUDGUARD_ID)
           CHKP_CLOUDGUARD_SECRET: $(CHKP_CLOUDGUARD_SECRET)
           SG_CLIENT_ID: $(SG_CLIENT_ID)
           SG_SECRET_KEY: $(SG_SECRET_KEY)
          continueOnError: True
    
    
    - job:  Deploy_to_Azure
      steps:
       - task: TerraformInstaller@0
         inputs:
          terraformVersion: '0.13.3'
      
       - bash: |
                sed -i "/token/c\   token\ = \"$TERRAFORM_API_KEY\"" main.tf                            
                cat main.tf
                terraform init
                terraform plan
                #terraform apply -auto-approve
         env: 
          TERRAFORM_API_KEY: $(TERRAFORM_API_KEY)