# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
        
stages:
  - stage: Security_Test
    jobs:
    
    - job: Terraform_Security_Scan  
      steps:
        - bash: |
              chmod +x ./shiftleft
              ./shiftleft iac-assessment -r 201981 --path ./
          env:
           CHKP_CLOUDGUARD_ID: $(CHKP_CLOUDGUARD_ID)
           CHKP_CLOUDGUARD_SECRET: $(CHKP_CLOUDGUARD_SECRET)
          continueOnError: True

    - job:  Deploy_to_Azure
      steps:
       - task: TerraformInstaller@0
         inputs:
          terraformVersion: '0.13.3'
      
       - bash: |
                ls /opt/hostedtoolcache/terraform/0.13.3/x64/
                #terraform init
                #terraform plan
                #terraform apply -auto-approve
         env: 
          TERRAFORM_API_KEY: $(TERRAFORM_API_KEY)